// Mocks generated by Mockito 5.4.6 from annotations
// in media_picker/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i17;

import 'package:dartz/dartz.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i14;
import 'package:media_picker/src/core/options/media_selection_options.dart'
    as _i9;
import 'package:media_picker/src/data/datasources/camera/camera_datasource.dart'
    as _i12;
import 'package:media_picker/src/data/datasources/compression/compression_datasource.dart'
    as _i16;
import 'package:media_picker/src/data/datasources/file_picker/file_picker_datasource.dart'
    as _i15;
import 'package:media_picker/src/data/datasources/gallery/gallery_datasource.dart'
    as _i13;
import 'package:media_picker/src/data/datasources/permission/permission_datasource.dart'
    as _i19;
import 'package:media_picker/src/data/models/image_dto.dart' as _i3;
import 'package:media_picker/src/data/models/mappers/image_mapper.dart' as _i20;
import 'package:media_picker/src/data/models/mappers/video_mapper.dart' as _i22;
import 'package:media_picker/src/data/models/video_dto.dart' as _i4;
import 'package:media_picker/src/domain/entities/media_entity.dart' as _i8;
import 'package:media_picker/src/domain/entities/media_metadata_entity.dart'
    as _i21;
import 'package:media_picker/src/domain/enums/permission_status.dart' as _i11;
import 'package:media_picker/src/domain/failures/media_failure.dart' as _i7;
import 'package:media_picker/src/domain/repositories/media_repository.dart'
    as _i5;
import 'package:media_picker/src/domain/repositories/permission_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImageDto_1 extends _i1.SmartFake implements _i3.ImageDto {
  _FakeImageDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVideoDto_2 extends _i1.SmartFake implements _i4.VideoDto {
  _FakeVideoDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaRepository extends _i1.Mock implements _i5.MediaRepository {
  MockMediaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>
  getMediasFromCamera({required _i9.MediaSelectionOptions? options}) =>
      (super.noSuchMethod(
            Invocation.method(#getMediasFromCamera, [], {#options: options}),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>
                >.value(
                  _FakeEither_0<_i7.MediaFailure, List<_i8.MediaEntity>>(
                    this,
                    Invocation.method(#getMediasFromCamera, [], {
                      #options: options,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>
  getMediasFromGallery({required _i9.MediaSelectionOptions? options}) =>
      (super.noSuchMethod(
            Invocation.method(#getMediasFromGallery, [], {#options: options}),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>
                >.value(
                  _FakeEither_0<_i7.MediaFailure, List<_i8.MediaEntity>>(
                    this,
                    Invocation.method(#getMediasFromGallery, [], {
                      #options: options,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>
  getMediasFromFiles({required _i9.MediaSelectionOptions? options}) =>
      (super.noSuchMethod(
            Invocation.method(#getMediasFromFiles, [], {#options: options}),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>
                >.value(
                  _FakeEither_0<_i7.MediaFailure, List<_i8.MediaEntity>>(
                    this,
                    Invocation.method(#getMediasFromFiles, [], {
                      #options: options,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, List<_i8.MediaEntity>>>);
}

/// A class which mocks [PermissionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionRepository extends _i1.Mock
    implements _i10.PermissionRepository {
  MockPermissionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, bool>> requestCamera() =>
      (super.noSuchMethod(
            Invocation.method(#requestCamera, []),
            returnValue: _i6.Future<_i2.Either<_i7.MediaFailure, bool>>.value(
              _FakeEither_0<_i7.MediaFailure, bool>(
                this,
                Invocation.method(#requestCamera, []),
              ),
            ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, bool>> requestPhotos() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhotos, []),
            returnValue: _i6.Future<_i2.Either<_i7.MediaFailure, bool>>.value(
              _FakeEither_0<_i7.MediaFailure, bool>(
                this,
                Invocation.method(#requestPhotos, []),
              ),
            ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, bool>> requestLocation() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocation, []),
            returnValue: _i6.Future<_i2.Either<_i7.MediaFailure, bool>>.value(
              _FakeEither_0<_i7.MediaFailure, bool>(
                this,
                Invocation.method(#requestLocation, []),
              ),
            ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, bool>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, _i11.PermissionStatus>>
  checkCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkCameraPermission, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.MediaFailure, _i11.PermissionStatus>
                >.value(
                  _FakeEither_0<_i7.MediaFailure, _i11.PermissionStatus>(
                    this,
                    Invocation.method(#checkCameraPermission, []),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, _i11.PermissionStatus>>);

  @override
  _i6.Future<_i2.Either<_i7.MediaFailure, _i11.PermissionStatus>>
  checkPhotosPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPhotosPermission, []),
            returnValue:
                _i6.Future<
                  _i2.Either<_i7.MediaFailure, _i11.PermissionStatus>
                >.value(
                  _FakeEither_0<_i7.MediaFailure, _i11.PermissionStatus>(
                    this,
                    Invocation.method(#checkPhotosPermission, []),
                  ),
                ),
          )
          as _i6.Future<_i2.Either<_i7.MediaFailure, _i11.PermissionStatus>>);
}

/// A class which mocks [CameraDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraDataSource extends _i1.Mock implements _i12.CameraDataSource {
  MockCameraDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.ImageDto> captureImage() =>
      (super.noSuchMethod(
            Invocation.method(#captureImage, []),
            returnValue: _i6.Future<_i3.ImageDto>.value(
              _FakeImageDto_1(this, Invocation.method(#captureImage, [])),
            ),
          )
          as _i6.Future<_i3.ImageDto>);

  @override
  _i6.Future<_i4.VideoDto> captureVideo({Duration? maxDuration}) =>
      (super.noSuchMethod(
            Invocation.method(#captureVideo, [], {#maxDuration: maxDuration}),
            returnValue: _i6.Future<_i4.VideoDto>.value(
              _FakeVideoDto_2(
                this,
                Invocation.method(#captureVideo, [], {
                  #maxDuration: maxDuration,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.VideoDto>);

  @override
  _i6.Future<bool> isCameraAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCameraAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [GalleryDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGalleryDataSource extends _i1.Mock implements _i13.GalleryDataSource {
  MockGalleryDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.ImageDto>> pickImages(int? maxImages) =>
      (super.noSuchMethod(
            Invocation.method(#pickImages, [maxImages]),
            returnValue: _i6.Future<List<_i3.ImageDto>>.value(<_i3.ImageDto>[]),
          )
          as _i6.Future<List<_i3.ImageDto>>);

  @override
  _i6.Future<List<_i4.VideoDto>> pickVideos(int? maxVideos) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideos, [maxVideos]),
            returnValue: _i6.Future<List<_i4.VideoDto>>.value(<_i4.VideoDto>[]),
          )
          as _i6.Future<List<_i4.VideoDto>>);

  @override
  _i6.Future<List<_i14.XFile>> pickMixedMedia({required int? maxItems}) =>
      (super.noSuchMethod(
            Invocation.method(#pickMixedMedia, [], {#maxItems: maxItems}),
            returnValue: _i6.Future<List<_i14.XFile>>.value(<_i14.XFile>[]),
          )
          as _i6.Future<List<_i14.XFile>>);
}

/// A class which mocks [FilePickerDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerDataSource extends _i1.Mock
    implements _i15.FilePickerDataSource {
  MockFilePickerDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.ImageDto>> pickFiles({
    required List<String>? allowedExtensions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #allowedExtensions: allowedExtensions,
            }),
            returnValue: _i6.Future<List<_i3.ImageDto>>.value(<_i3.ImageDto>[]),
          )
          as _i6.Future<List<_i3.ImageDto>>);
}

/// A class which mocks [CompressionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompressionDataSource extends _i1.Mock
    implements _i16.CompressionDataSource {
  MockCompressionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i17.Uint8List> compress(_i17.Uint8List? data) =>
      (super.noSuchMethod(
            Invocation.method(#compress, [data]),
            returnValue: _i6.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
          )
          as _i6.Future<_i17.Uint8List>);

  @override
  _i6.Future<String> compressToFile(String? sourcePath) =>
      (super.noSuchMethod(
            Invocation.method(#compressToFile, [sourcePath]),
            returnValue: _i6.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#compressToFile, [sourcePath]),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [PermissionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionDataSource extends _i1.Mock
    implements _i19.PermissionDataSource {
  MockPermissionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> requestPhotosPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPhotosPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i11.PermissionStatus> checkCameraPermissionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkCameraPermissionStatus, []),
            returnValue: _i6.Future<_i11.PermissionStatus>.value(
              _i11.PermissionStatus.notDetermined,
            ),
          )
          as _i6.Future<_i11.PermissionStatus>);

  @override
  _i6.Future<_i11.PermissionStatus> checkPhotosPermissionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkPhotosPermissionStatus, []),
            returnValue: _i6.Future<_i11.PermissionStatus>.value(
              _i11.PermissionStatus.notDetermined,
            ),
          )
          as _i6.Future<_i11.PermissionStatus>);
}

/// A class which mocks [ImageMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageMapper extends _i1.Mock implements _i20.ImageMapper {
  MockImageMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MediaEntity dtoToEntity(
    _i3.ImageDto? dto, {
    _i21.MediaMetadataEntity? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dtoToEntity, [dto], {#metadata: metadata}),
            returnValue: _i18.dummyValue<_i8.MediaEntity>(
              this,
              Invocation.method(#dtoToEntity, [dto], {#metadata: metadata}),
            ),
          )
          as _i8.MediaEntity);

  @override
  _i3.ImageDto entityToDto(_i8.ImageMedia? entity) =>
      (super.noSuchMethod(
            Invocation.method(#entityToDto, [entity]),
            returnValue: _FakeImageDto_1(
              this,
              Invocation.method(#entityToDto, [entity]),
            ),
          )
          as _i3.ImageDto);
}

/// A class which mocks [VideoMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoMapper extends _i1.Mock implements _i22.VideoMapper {
  MockVideoMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MediaEntity dtoToEntity(
    _i4.VideoDto? dto, {
    _i21.MediaMetadataEntity? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dtoToEntity, [dto], {#metadata: metadata}),
            returnValue: _i18.dummyValue<_i8.MediaEntity>(
              this,
              Invocation.method(#dtoToEntity, [dto], {#metadata: metadata}),
            ),
          )
          as _i8.MediaEntity);

  @override
  _i4.VideoDto entityToDto(_i8.VideoMedia? entity) =>
      (super.noSuchMethod(
            Invocation.method(#entityToDto, [entity]),
            returnValue: _FakeVideoDto_2(
              this,
              Invocation.method(#entityToDto, [entity]),
            ),
          )
          as _i4.VideoDto);
}
